name: build centos

on: 
  push:

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extras: [mecab, juman]
    steps:
    - uses: actions/checkout@v1
    - run: docker build -f dockerfiles/centos/Dockerfile .
    - run: docker run maturin publish --manylinux off ---no-sdist --repository-url https://test.pypi.org/legacy/ -u ${{ secrets.TEST_PYPI_USER }} -p ${{ secrets.TEST_PYPI_PASS }}
    - run: docker run maturin publish --manylinux off ---no-sdist -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASS }}
