name: build manylinux

on: 
  push:

jobs:
  build:
    # if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonpath: 
          - cp35-cp35m
          - cp36-cp36m
          - cp37-cp37m
          - cp38-cp38
    container: 
      image: quay.io/pypa/manylinux1_x86_64:2020-03-07-9c5ba95
      env:
        PATH: /root/.cargo/bin:/root/.local/bin:/opt/python/${{ matrix.pythonpath }}/bin:/opt/python/cp36-cp36m/bin:/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    env:
      PATH: /home/runner/.local/bin:/usr/share/rust/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/python/${{ matrix.pythonpath }}/bin
    steps:
    - run: |
        echo $USER
        echo $PATH
        echo $HOME
        ls /opt/python
        exit 1
    - uses: actions/checkout@v1
    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly --profile minimal -y
        rustup default nightly

    # - name: Test rust lib
    #   run: cargo test

    - name: Install dependencies with pip
      working-directory: python
      run: |
        which python3
        python3 -m pip install --upgrade pip
        python3 -m pip install poetry maturin --user
        poetry install

    - name: Build python package
      working-directory: python
      run: poetry run maturin develop

    - name: Test with pytest
      working-directory: python
      run: poetry run pytest tests

    - name: Install publishment tool
      working-directory: python
      run: |
        pip install twine

    - name: Build
      run: |
        maturin build --no-sdist --release --strip 
        find target/ -type f -name "*whl" -exec python3 -m auditwheel repair {} +

    - name: Publish test pypi
      working-directory: python
      run: |
        twine upload --repository-url https://test.pypi.org/legacy/ -u ${{ secrets.TEST_PYPI_USER }} -p ${{ secrets.TEST_PYPI_PASS }}

    - name: Publish pypi
      working-directory: python
      run: |
        pip install twine
        twine upload -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASS }} target/wheels/*


