name: build manylinux

on: 
  push:

jobs:
  build:
    # if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonpath: 
          - cp35-cp35m
          - cp36-cp36m
          - cp37-cp37m
          - cp38-cp38
    container: 
      image: quay.io/pypa/manylinux1_x86_64:2020-03-07-9c5ba95
      env:
        PATH: /root/.cargo/bin:/root/.local/bin:$PATH:/opt/python/${{ matrix.pythonpath }}/bin:/opt/python/cp36-cp36m/bin:/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38/bin
    steps:
    - uses: actions/checkout@v1
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true

    - name: Test with cargo
      uses: actions-rs/cargo@v1.0.1
      with:
          command: test
          toolchain: nightly

    - name: Install dependencies with pip
      working-directory: python
      run: |
        python -m pip install --upgrade pip
        pip install poetry maturin
        poetry install

    - name: Build python package
      working-directory: python
      run: poetry run maturin develop

    - name: Test with pytest
      working-directory: python
      run: poetry run pytest tests

    - name: Install publishment tool
      working-directory: python
      run: |
        pip install twine

    - name: Build
      run: |
        maturin build --no-sdist --release --strip 
        find target/ -type f -name "*whl" -exec python3 -m auditwheel repair {} +

    - name: Publish test pypi
      working-directory: python
      run: |
        twine upload --repository-url https://test.pypi.org/legacy/ -u ${{ secrets.TEST_PYPI_USER }} -p ${{ secrets.TEST_PYPI_PASS }}

    - name: Publish pypi
      working-directory: python
      run: |
        pip install twine
        twine upload -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASS }} target/wheels/*


