name: build manylinux

on: 
  push:

jobs:
  build:
    # if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker build -f dockerfiles/manylinux/Dockerfile -t tokenizations .
    - run: docker run tokenizations twine upload target/wheels/* --repository-url https://test.pypi.org/legacy/ -u ${{ secrets.TEST_PYPI_USER }} -p ${{ secrets.TEST_PYPI_PASS }}
    - run: docker run tokenizations twine upload target/wheels/* -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASS }}
